package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import processor "github.com/MasterOfBinary/gobatch/processor"

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx, items
func (_m *Processor) Process(ctx context.Context, items []interface{}) error {
	ret := _m.Called(ctx, items)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []interface{}) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ processor.Processor = (*Processor)(nil)
