language: go
sudo: false

go:
 - 1.8.x
 - 1.8
 - 1.7.x
 - 1.7

before_install:
 - go get github.com/mattn/goveralls

install:
 - go get -t ./...
 - go get -u gopkg.in/alecthomas/gometalinter.v1
 - gometalinter --install

script:
 - go test -v -race ./...
 - gometalinter ./...

after_script:
 - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false