language: go
sudo: false

go:
 - 1.15.x
 - 1.15
 - 1.14.x
 - 1.11.x
 - 1.7.x

before_install:
 - go get -u github.com/mattn/goveralls
 - go get -u gopkg.in/alecthomas/gometalinter.v1

install:
 - go get -t ./...
 - gometalinter.v1 --install

script:
 - go test -v -race ./...
 - gometalinter.v1 --disable=gocyclo ./...

after_script:
 - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false