language: go
sudo: false

go:
 - 1.8.x
 - 1.8
 - 1.7.x
 - 1.7

before_install:
 - go get -u github.com/mattn/goveralls
 - go get -u gopkg.in/alecthomas/gometalinter.v1

install:
 - go get -u -t ./...
 - gometalinter.v1 --install

script:
 - go test -v -race ./...
 - gometalinter.v1 ./...

after_script:
 - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false