language: go

go:
  - 1.18.x
  - 1.19.x
  - 1.20.x
  - 1.21.x
  - tip

before_install:
  - go get -u github.com/mattn/goveralls
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - go get -t -v ./...

install:
  - gometalinter.v1 --install

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - gometalinter.v1 --disable=gocyclo ./...

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email:
    on_success: change
    on_failure: always