package source

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

// Read provides a mock function with given fields: ctx, items, errs
func (_m *MockSource) Read(ctx context.Context, items chan<- interface{}, errs chan<- error) {
	_m.Called(ctx, items, errs)
}

var _ Source = (*MockSource)(nil)
